# Generated by Django 3.2.7 on 2021-09-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.TextField(verbose_name='Имя друга')),
            ],
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.TextField(verbose_name='Издательство'),
        ),
        migrations.AddField(
            model_name='book',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='p_library.friend', verbose_name='Одолжил'),
        ),
    ]
